apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: opusmastery-api-ingressroute
  namespace: opusmastery-api
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api.opusmastery.org`)
      kind: Rule
      services:
        - name: opusmastery-api
          port: 80
  tls:
    certResolver: letsencrypt
