name: opusmastery-api

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: self-hosted
    env:
      DOCKER_REPOSITORY_NAME: zvesdochyot/$GITHUB_WORKFLOW

    steps:
    - name: Checkout existing code
      uses: actions/checkout@v3

    - name: Build Docker image
      run:
        docker build ./OpusMastery/OpusMastery.Admin/ --file ./OpusMastery/OpusMastery.Admin/Dockerfile -t $DOCKER_REPOSITORY_NAME:$GITHUB_RUN_NUMBER

#     - name: Setup .NET Core SDK
#       uses: actions/setup-dotnet@v3.0.3
#       with:
#         dotnet-version: 7.x
#       env:
#         DOTNET_INSTALL_DIR: "./.dotnet"
