name: opusmastery-api

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build & publish
    runs-on: self-hosted
    env:
      DOCKER_REPOSITORY_OWNER: ${{ secrets.DOCKER_REPOSITORY_OWNER }}
      DOCKER_REPOSITORY_PASSWORD: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}

    steps:
      - name: Checkout existing code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build ./OpusMastery/ --file ./OpusMastery/Dockerfile -t $DOCKER_REPOSITORY_OWNER/$GITHUB_WORKFLOW:v$GITHUB_RUN_NUMBER

      - name: Push Docker image to Docker Hub
        run: |
          docker login -u $DOCKER_REPOSITORY_OWNER -p $DOCKER_REPOSITORY_PASSWORD
          docker push $DOCKER_REPOSITORY_OWNER/$GITHUB_WORKFLOW:v$GITHUB_RUN_NUMBER

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout existing code
        uses: actions/checkout@v3

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3
        with:
           version: '1.26.4'

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_VALUE }}

      - name: Deploy to K3s cluster
        uses: Azure/k8s-deploy@v4.9
        with:
          action: deploy
          manifests: |
            manifests/deployment.yaml
            manifests/ingress.yaml
          strategy: canary
          namespace: $GITHUB_WORKFLOW
          images: $DOCKER_REPOSITORY_OWNER/$GITHUB_WORKFLOW:v$GITHUB_RUN_NUMBER
          percentage: 50
